name: checks

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v4
      - name: Build for testing
        run: xcodebuild build-for-testing -scheme swiftui-snap-dragging-modifier -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' -derivedDataPath .build/xcode-ci
      - name: Test
        run: xcodebuild test-without-building -scheme swiftui-snap-dragging-modifier -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' -derivedDataPath .build/xcode-ci
